name: meld-dev
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meld_dev
    ports:
      - "5432:5432" # change left side if 5432 is taken (e.g., 5433:5432)
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
