version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:20.19.5
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm ci

workflows:
  version: 2
  install_dependencies_workflow:
    jobs:
      - install_dependencies